# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton
from PyQt5.QtGui import QIcon, QPixmap, QPainter
import sqlite3
from PIL import Image

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QIcon
from PIL import Image
from random import choice


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.my_counter = Management()
        self.face_im_name_num = 0
        self.flag_extra_image = 0
        self.count_error = 0
        self.random_count = 0

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(60, 50, 240, 50))
        self.comboBox.setObjectName("comboBox")

        MainWindow.setWindowIcon(QIcon('imgs\web.jpeg'))

        # first face btn
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 30, 50))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.counting_face_plus)
        self.pushButton.clicked.connect(self.im_face)

        # second face btn
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 50, 30, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.counting_face_minus)
        self.pushButton_2.clicked.connect(self.im_face)

        # first hair btn
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 30, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.hair_im_name_num = 0
        self.pushButton_3.clicked.connect(self.counting_hair_plus)
        self.pushButton_3.clicked.connect(self.im_hair)

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 130, 240, 50))
        self.comboBox_2.setObjectName("comboBox_2")

        # second hair btn
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 130, 30, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.counting_hair_minus)
        self.pushButton_4.clicked.connect(self.im_hair)

        # second eyes btn
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 210, 30, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.eyes_im_name_num = 0
        self.pushButton_5.clicked.connect(self.counting_eyes_minus)
        self.pushButton_5.clicked.connect(self.im_eyes)

        # first eyes btn
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 210, 30, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.counting_eyes_plus)
        self.pushButton_6.clicked.connect(self.im_eyes)

        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(60, 210, 240, 50))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 240, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 240, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 180, 240, 25))
        self.label_3.setObjectName("label_3")

        # SAVE btn
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(840, 370, 100, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.saving)

        # first ears btn
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 290, 30, 50))
        self.pushButton_14.setObjectName("pushButton_14")
        self.ears_im_name_num = 0
        self.pushButton_14.clicked.connect(self.counting_ears_plus)
        self.pushButton_14.clicked.connect(self.im_ears)

        # second ears btn
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(310, 290, 30, 50))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.counting_ears_minus)
        self.pushButton_15.clicked.connect(self.im_ears)

        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(60, 290, 240, 50))
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 260, 240, 25))
        self.label_7.setObjectName("label_7")

        # first eyebrows btn
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(620, 50, 30, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.eyebrows_im_name_num = 0
        self.pushButton_7.clicked.connect(self.counting_eyebrows_plus)
        self.pushButton_7.clicked.connect(self.im_eyebrows)

        # first nose btn
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(620, 210, 30, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.nose_im_name_num = 0
        self.pushButton_8.clicked.connect(self.counting_nose_plus)
        self.pushButton_8.clicked.connect(self.im_nose)

        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(660, 50, 240, 50))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(660, 290, 240, 50))
        self.comboBox_8.setObjectName("comboBox_8")

        # first attribute btn
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(620, 290, 30, 50))
        self.pushButton_16.setObjectName("pushButton_16")
        self.attribute_im_name_num = 0
        self.pushButton_16.clicked.connect(self.counting_attribute_plus)
        self.pushButton_16.clicked.connect(self.im_attribute)

        # second mouth btn
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(910, 130, 30, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.mouth_im_name_num = 0
        self.pushButton_9.clicked.connect(self.counting_mouth_minus)
        self.pushButton_9.clicked.connect(self.im_mouth)

        # second nose btn
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(910, 210, 30, 50))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.counting_nose_minus)
        self.pushButton_10.clicked.connect(self.im_nose)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 20, 240, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(660, 100, 240, 25))
        self.label_5.setObjectName("label_5")

        # second attribute btn
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(910, 290, 30, 50))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.counting_attribute_minus)
        self.pushButton_17.clicked.connect(self.im_attribute)

        # first mouth btn
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(620, 130, 30, 50))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.counting_mouth_plus)
        self.pushButton_11.clicked.connect(self.im_mouth)

        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(660, 210, 240, 50))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(660, 130, 240, 50))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 180, 240, 25))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(660, 260, 240, 25))
        self.label_8.setObjectName("label_8")

        # second eyebrows btn
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(910, 50, 30, 50))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.counting_eyebrows_minus)
        self.pushButton_12.clicked.connect(self.im_eyebrows)

        # RANDOM button
        self.Random_button = QtWidgets.QPushButton(self.centralwidget)
        self.Random_button.setGeometry(QtCore.QRect(730, 370, 100, 30))
        self.Random_button.setObjectName("Random_button")
        self.Random_button.clicked.connect(self.random)

        # Error label
        self.Error_label = QtWidgets.QLabel(self.centralwidget)
        self.Error_label.setGeometry(QtCore.QRect(20, 370, 470, 30))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Error_label.setFont(font)
        self.Error_label.setStyleSheet("font: 11pt \"MS Serif\";\n"
                                       "color: rgb(255, 56, 56);")
        self.Error_label.setObjectName("Error_label")

        # ERROR button
        self.Error_button = QtWidgets.QPushButton(self.centralwidget)
        self.Error_button.setGeometry(QtCore.QRect(490, 380, 30, 15))
        self.Error_button.setStyleSheet("font: 10pt \"MS Serif\";\n"
                                        "color: rgb(255, 56, 56);")
        self.Error_button.setObjectName("Error_button")
        self.Error_button.clicked.connect(self.error_button)

        # Second error label
        self.Error_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Error_label_2.setGeometry(QtCore.QRect(100, 370, 470, 30))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Error_label_2.setFont(font)
        self.Error_label_2.setStyleSheet("font: 11pt \"MS Serif\";\n"
                                         "color: rgb(255, 56, 56);")
        self.Error_label_2.setObjectName("Error_label_2")

        # easter egg :))))))))
        self.Funny_label = QtWidgets.QLabel(self.centralwidget)
        self.Funny_label.setGeometry(QtCore.QRect(600, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Funny_label.setFont(font)
        self.Funny_label.setStyleSheet("font: 100 12pt \"System\";\n"
                                       "font: 75 12pt \"System\";\n"
                                       "color: rgb(0, 154, 12);\n"
                                       "")
        self.Funny_label.setObjectName("Funny_label")
        MainWindow.setCentralWidget(self.centralwidget)

        #funny btn1
        self.funny_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.funny_button1.setGeometry(QtCore.QRect(310, 370, 141, 30))
        self.funny_button1.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";\n"
                                         "color: rgb(0, 0, 194);")
        self.funny_button1.setObjectName("funny_button1")
        self.funny_button1.clicked.connect(self.f_b_1)

        # funny btn2
        self.funny_button2 = QtWidgets.QPushButton(self.centralwidget)
        self.funny_button2.setGeometry(QtCore.QRect(460, 370, 51, 30))
        self.funny_button2.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
                                         "color: rgb(0, 0, 194);")
        self.funny_button2.setObjectName("funny_button2")
        self.funny_button2.clicked.connect(self.yes)

        # funny label
        self.No_label = QtWidgets.QLabel(self.centralwidget)
        self.No_label.setGeometry(QtCore.QRect(260, 370, 41, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.No_label.setFont(font)
        self.No_label.setStyleSheet("font: 11pt \"MS Serif\";\n"
                                    "color: rgb(255, 56, 56);")
        self.No_label.setObjectName("No_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.Error_label.setVisible(False)
        self.Error_label_2.setVisible(False)
        self.Error_button.setVisible(False)
        self.Funny_label.setVisible(False)
        self.funny_button1.setVisible(False)
        self.funny_button2.setVisible(False)
        self.No_label.setVisible(False)



        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        # background
        self.mainlabel_background = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_background.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_background.setObjectName("Main_Label")
        self.mainlabel_background.setPixmap(QPixmap('imgs\sbackground.jpg'))


        # face
        self.mainlabel_face = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_face.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_face.setObjectName("Main_Label")

        # eyes
        self.mainlabel_eyes = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_eyes.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_eyes.setObjectName("Main_Label")

        # ears
        self.mainlabel_ears = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_ears.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_ears.setObjectName("Main_Label")

        # eyebrows
        self.mainlabel_eyebrows = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_eyebrows.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_eyebrows.setObjectName("Main_Label")

        # mouth
        self.mainlabel_mouth = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_mouth.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_mouth.setObjectName("Main_Label")

        # nose
        self.mainlabel_nose = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_nose.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_nose.setObjectName("Main_Label")

        # hair
        self.mainlabel_hair = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_hair.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_hair.setObjectName("Main_Label")

        # attributes
        self.mainlabel_attribute = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_attribute.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_attribute.setObjectName("Main_Label")
        self.attribute_im_name = 'sattribute3.png'
        self.mainlabel_attribute.setPixmap(QPixmap('imgs\sattribute3.png'))

        self.mainlabel_i = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_i.setGeometry(QtCore.QRect(360, 20, 240, 320))
        self.mainlabel_i.setObjectName("Main_Label")



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.centrelpic = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel_attribute.setGeometry(QtCore.QRect(360, 20, 240, 320))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мультяшный фоторобот"))
        self.pushButton.setText(_translate("MainWindow", "<"))
        self.pushButton_2.setText(_translate("MainWindow", ">"))
        self.pushButton_3.setText(_translate("MainWindow", "<"))
        self.pushButton_4.setText(_translate("MainWindow", ">"))
        self.pushButton_5.setText(_translate("MainWindow", ">"))
        self.pushButton_6.setText(_translate("MainWindow", "<"))
        self.label.setText(_translate("MainWindow", "Face"))
        self.label_2.setText(_translate("MainWindow", "Hair"))
        self.label_3.setText(_translate("MainWindow", "Eyes"))
        self.pushButton_13.setText(_translate("MainWindow", "Save"))
        self.pushButton_14.setText(_translate("MainWindow", "<"))
        self.pushButton_15.setText(_translate("MainWindow", ">"))
        self.label_7.setText(_translate("MainWindow", "Ears"))
        self.pushButton_7.setText(_translate("MainWindow", "<"))
        self.pushButton_8.setText(_translate("MainWindow", "<"))
        self.pushButton_16.setText(_translate("MainWindow", "<"))
        self.pushButton_9.setText(_translate("MainWindow", ">"))
        self.pushButton_10.setText(_translate("MainWindow", ">"))
        self.label_4.setText(_translate("MainWindow", "Eyebrows"))
        self.label_5.setText(_translate("MainWindow", "Mouth"))
        self.pushButton_17.setText(_translate("MainWindow", ">"))
        self.pushButton_11.setText(_translate("MainWindow", "<"))
        self.label_6.setText(_translate("MainWindow", "Nose"))
        self.label_8.setText(_translate("MainWindow", "Attributes"))
        self.pushButton_12.setText(_translate("MainWindow", ">"))
        self.Random_button.setText(_translate("MainWindow", "Random"))
        self.Error_label.setText(_translate("MainWindow", "Please finish the character. I don't like to keep things unfinished..."))
        self.Error_button.setText(_translate("MainWindow", "OK"))
        self.Error_label_2.setText(_translate("MainWindow", "What are you doing 0_o?"))
        self.Funny_label.setText(_translate("MainWindow", "I think it\'s funny :)"))
        self.funny_button1.setText(_translate("MainWindow", "I\'m testing your program"))
        self.funny_button2.setText(_translate("MainWindow", "yes"))
        self.No_label.setText(_translate("MainWindow", "No:)"))

    def resize(self, param, param1):
        pass

    def counting_face_plus(self):
        self.face_im_name_num += 1
        p_of_n = 1
        self.num_face = int(str(p_of_n) + str(self.face_im_name_num % 3 + 1))
        self.face_im_name = self.my_counter.definition(self.num_face)

    def counting_face_minus(self):
        self.face_im_name_num -= 1
        p_of_n = 1
        self.num_face = int(str(p_of_n) + str(self.face_im_name_num % 3 + 1))
        self.face_im_name = self.my_counter.definition(self.num_face)

    def counting_hair_plus(self):
        p_of_n = 2
        self.hair_im_name_num += 1
        self.num_hair = int(str(p_of_n) + str(self.hair_im_name_num % 3 + 1))
        self.hair_im_name = self.my_counter.definition(self.num_hair)

    def counting_hair_minus(self):
        p_of_n = 2
        self.hair_im_name_num -= 1
        self.num_hair = int(str(p_of_n) + str(self.hair_im_name_num % 3 + 1))
        self.hair_im_name = self.my_counter.definition(self.num_hair)

    def counting_ears_plus(self):
        p_of_n = 3
        self.ears_im_name_num += 1
        self.num_ears = int(str(p_of_n) + str(self.ears_im_name_num % 3 + 1))
        self.ears_im_name = self.my_counter.definition(self.num_ears)

    def counting_ears_minus(self):
        p_of_n = 3
        self.ears_im_name_num -= 1
        self.num_ears = int(str(p_of_n) + str(self.ears_im_name_num % 3 + 1))
        self.ears_im_name = self.my_counter.definition(self.num_ears)

    def counting_eyes_plus(self):
        p_of_n = 4
        self.eyes_im_name_num += 1
        self.num_eyes = int(str(p_of_n) + str(self.eyes_im_name_num % 3 + 1))
        self.eyes_im_name = self.my_counter.definition(self.num_eyes)

    def counting_eyes_minus(self):
        p_of_n = 4
        self.eyes_im_name_num -= 1
        self.num_eyes = int(str(p_of_n) + str(self.eyes_im_name_num % 3 + 1))
        self.eyes_im_name = self.my_counter.definition(self.num_eyes)

    def counting_eyebrows_plus(self):
        p_of_n = 5
        self.eyebrows_im_name_num += 1
        self.num_eyebrows = int(str(p_of_n) + str(self.eyebrows_im_name_num % 3 + 1))
        self.eyebrows_im_name = self.my_counter.definition(self.num_eyebrows)

    def counting_eyebrows_minus(self):
        p_of_n = 5
        self.eyebrows_im_name_num -= 1
        self.num_eyebrows = int(str(p_of_n) + str(self.eyebrows_im_name_num % 3 + 1))
        self.eyebrows_im_name = self.my_counter.definition(self.num_eyebrows)

    def counting_mouth_plus(self):
        p_of_n = 6
        self.mouth_im_name_num += 1
        self.num_mouth = int(str(p_of_n) + str(self.mouth_im_name_num % 3 + 1))
        self.mouth_im_name = self.my_counter.definition(self.num_mouth)

    def counting_mouth_minus(self):
        p_of_n = 6
        self.mouth_im_name_num -= 1
        self.num_mouth = int(str(p_of_n) + str(self.mouth_im_name_num % 3 + 1))
        self.mouth_im_name = self.my_counter.definition(self.num_mouth)

    def counting_nose_plus(self):
        p_of_n = 7
        self.nose_im_name_num += 1
        self.num_nose = int(str(p_of_n) + str(self.nose_im_name_num % 3 + 1))
        self.nose_im_name = self.my_counter.definition(self.num_nose)

    def counting_nose_minus(self):
        p_of_n = 7
        self.nose_im_name_num -= 1
        self.num_nose = int(str(p_of_n) + str(self.nose_im_name_num % 3 + 1))
        self.nose_im_name = self.my_counter.definition(self.num_nose)

    def counting_attribute_plus(self):
        p_of_n = 8
        self.attribute_im_name_num += 1
        self.num_attribute = int(str(p_of_n) + str(self.attribute_im_name_num % 3 + 1))
        self.attribute_im_name = self.my_counter.definition(self.num_attribute)

    def counting_attribute_minus(self):
        p_of_n = 8
        self.attribute_im_name_num -= 1
        self.num_attribute = int(str(p_of_n) + str(self.attribute_im_name_num % 3 + 1))
        self.attribute_im_name = self.my_counter.definition(self.num_attribute)

    def error_button(self):
        self.Error_label.setVisible(False)
        self.Error_button.setVisible(False)
        self.Error_button.setGeometry(QtCore.QRect(490, 380, 30, 15))

    def yes(self):
        self.No_label.setVisible(True)
        self.funny_button2.setVisible(False)
        self.funny_button1.setVisible(False)
        self.Error_label_2.setVisible(False)

    def f_b_1(self):
        self.funny_button2.setVisible(False)
        self.funny_button1.setVisible(False)
        self.Error_label_2.setVisible(False)
        self.Error_button.setGeometry(QtCore.QRect(200, 380, 40, 30))
        self.Error_button.setVisible(True)

    def random(self):
        self.random_count += 1
        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(1) + str(self.random_num))
        self.face_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_face.setPixmap(QPixmap(f'imgs\{self.face_im_name}'))
        self.mainlabel_i.setPixmap(QPixmap('imgs\important.png'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(2) + str(self.random_num))
        self.hair_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_hair.setPixmap(QPixmap(f'imgs\{self.hair_im_name}'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(3) + str(self.random_num))
        self.ears_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_ears.setPixmap(QPixmap(f'imgs\{self.ears_im_name}'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(4) + str(self.random_num))
        self.eyes_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_eyes.setPixmap(QPixmap(f'imgs\{self.eyes_im_name}'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(5) + str(self.random_num))
        self.eyebrows_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_eyebrows.setPixmap(QPixmap(f'imgs\{self.eyebrows_im_name}'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(6) + str(self.random_num))
        self.mouth_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_mouth.setPixmap(QPixmap(f'imgs\{self.mouth_im_name}'))

        self.random_num = choice((1, 2, 3))
        self.rez_random_num = int(str(7) + str(self.random_num))
        self.nose_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_nose.setPixmap(QPixmap(f'imgs\{self.nose_im_name}'))

        self.rez_random_num = int(str(8) + str(3))
        self.attribute_im_name = self.my_counter.definition(self.rez_random_num).strip()
        self.mainlabel_attribute.setPixmap(QPixmap(f'imgs\{self.attribute_im_name}'))
        if self.random_count == 20:
            self.Funny_label.setVisible(True)
        if self.random_count == 21:
            self.Funny_label.setVisible(False)


    def im_face(self):
        name = self.face_im_name.strip()
        print(name)
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_face.setPixmap(pixmap)
        if self.flag_extra_image != 2:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important.png'))
            self.flag_extra_image = 2

    def im_hair(self):
        name = self.hair_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_hair.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_eyes(self):
        name = self.eyes_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_eyes.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_ears(self):
        name = self.ears_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_ears.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_eyebrows(self):
        name = self.eyebrows_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_eyebrows.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_mouth(self):
        name = self.mouth_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_mouth.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_nose(self):
        name = self.nose_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_nose.setPixmap(pixmap)
        if self.flag_extra_image == 0:
            self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))
            self.flag_extra_image = 1

    def im_attribute(self):
        name = self.attribute_im_name.strip()
        pixmap = QPixmap(f'imgs\{name}')
        self.mainlabel_attribute.setPixmap(pixmap)
        self.mainlabel_i.setPixmap(QPixmap('imgs\important1.png'))


    def setWindowIcon(self, param):
        pass

    def saving(self):
        try:
            img = Image.new('RGB', (240, 320))
            rez_face = Image.open(f'imgs\{self.face_im_name}'.strip())
            rez_eyes = Image.open(f'imgs\{self.eyes_im_name}'.strip())
            rez_ears = Image.open(f'imgs\{self.ears_im_name}'.strip())
            rez_eyebrows = Image.open(f'imgs\{self.eyebrows_im_name}'.strip())
            rez_mouth = Image.open(f'imgs\{self.mouth_im_name}'.strip())
            rez_nose = Image.open(f'imgs\{self.nose_im_name}'.strip())
            rez_hair = Image.open(f'imgs\{self.hair_im_name}'.strip())
            rez_attribute = Image.open(f'imgs\{self.attribute_im_name}'.strip())
            img.paste(rez_face, (0, 0))
            img.paste(rez_eyes, (0, 0), rez_eyes)
            img.paste(rez_ears, (0, 0), rez_ears)
            img.paste(rez_eyebrows, (0, 0), rez_eyebrows)
            img.paste(rez_mouth, (0, 0), rez_mouth)
            img.paste(rez_nose, (0, 0), rez_nose)
            img.paste(rez_hair, (0, 0), rez_hair)
            img.paste(rez_attribute, (0, 0), rez_attribute)

            img.show()
            img.save("My character.jpg")
        except AttributeError:
            self.count_error += 1
            self.Error_label.setVisible(True)
            self.Error_button.setVisible(True)
            print(self.count_error)
            if self.count_error > 9:
                self.Error_label_2.setVisible(True)
                self.Error_label.setVisible(False)
                self.funny_button1.setVisible(True)
                self.funny_button2.setVisible(True)
                self.Error_button.setVisible(False)


class Management:
    def definition(self, num):
        self.data = open('data.txt', encoding='utf-8')
        self.image_name = None
        for row in self.data:
            row_l = row.split('*')
            number = row_l[0]
            if int(number) == num:
                self.image_name = row_l[1]
        self.data.close()
        return self.image_name


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())
